ecommerce_e/customer/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('', views.home, name="home"),
    path('register', views.RegisterPage, name="register"),
    path('login', views.LoginPage, name="login"),
    path('logout', views.UserLogout, name="logout"),
    path('shop', views.shop, name="shop"),
    path('blog', views.blog, name="blog"),
    path('contact-us', views.contactus, name="contactus"),
    path('newsletter', views.newsletter, name="newsletter"),
    path('shop-detail/<int:id>/', views.shopdetail, name="shopdetail"),
    path('category-view/<int:id>/', views.categoryview, name="category-view"),
    path('cart', views.cart, name="cart"),
    path('add/<int:id>/', views.add_to_cart, name="add-to-cart"),
    path('remove/<int:id>/', views.cart_remove, name="remove-cart"),
    path('delete/<int:id>/', views.cart_delete, name="delete-cart"),
    path('wishlist', views.wishlist, name="wishlist"),
    path('addwishlist/<int:id>/', views.add_to_wishlist, name="add-wishlist"),
    path('removewishlist/<int:id>/', views.delete_from_wishlist, name="remove-wishlist"),
    path('movecart/<int:id>/', views.move_to_cart, name="move-cart"),
    path('checkout', views.checkout, name="checkout"),
    path('my-orders', views.my_orders, name="my-orders"),
    path('my-profile', views.my_profile, name="my-profile"),
    path("update-profile/<int:id>/",views.UpdateProfile.as_view(), name="update-profile"),
    path("blog-category/<int:id>/",views.blog_category, name="blog_category"),












    

    # Password reset paths
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name='forgot_password_reset.html'),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='password_reset_complete.html'),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),


    



    



   

]
  

ecommerce_e/ecommerce_e/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('customer.urls')),
    path('payments/', include('paymentsapp.urls')),
    path('owner/', include('owner.urls')),

]

urlpatterns += i18n_patterns (
    path('', include('customer.urls')),
)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ecommerce_e/owner/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name="dashboard"),
    path("manage-category",views.ManageCategory, name="manage-category"),
    path("add-category",views.AddCategory, name="add-category"),
    path("update-category/<int:id>/",views.UpdateCategory.as_view(), name="update-category"),
    path("delete-category/<int:id>/",views.DeleteCategory.as_view(), name="delete-category"),
    path("manage-products",views.ManageProducts, name="manage-products"),
    path("add-product",views.AddProduct, name="add-product"),
    path("update-product/<int:id>/",views.UpdateProduct.as_view(), name="update-product"),
    path("delete-product/<int:id>/",views.DeleteProduct.as_view(), name="delete-product"),
    path("manage-blogs",views.ManageBlogs, name="manage-blogs"),
    path("add-blog",views.AddBlog, name="add-blog"),
    path("update-blog/<int:id>/",views.UpdateBlog.as_view(), name="update-blog"),
    path("delete-blog/<int:id>/",views.DeleteBlog.as_view(), name="delete-blog"),
    path("manage-subscribe",views.ManageSubscribe, name="manage-subscribe"),
    path("manage-enquiries",views.ManageEnquiries, name="manage-enquiries"),
    path("view-enquiry/<int:id>/",views.ViewEnquiry, name="view-enquiry"),
    




]

ecommerce_e/customer/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Blogs(models.Model):
    name = models.CharField(max_length=50)
    category = models.CharField(max_length=50)
    image = models.ImageField(upload_to="images/")
    desc = models.CharField(max_length=200)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

class Contact(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    subject = models.CharField(max_length=200)
    message = models.TextField()
    options = (
        ("unread", "unread"),
        ("viewed", "viewed"),
    )
    status = models.CharField(max_length=20, choices=options, default="unread")
    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to="images/")
    desc = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Products(models.Model):
    name = models.CharField(max_length=50)
    featured = models.BooleanField(default=False)
    top_selled = models.BooleanField(default=False)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image_1 = models.ImageField(upload_to="images/")
    image_2 = models.ImageField(upload_to="images/")
    image_3 = models.ImageField(upload_to="images/")
    image_4 = models.ImageField(upload_to="images/")
    price = models.FloatField()
    available = models.BooleanField(default=True)
    desc = models.CharField(max_length=200)
    information = models.TextField()
    width = models.FloatField()
    height = models.FloatField()
    weight = models.FloatField()
    material = models.CharField(max_length=50)
    benefits = models.TextField()
    quality_check = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class NewsLetter(models.Model):
    email = models.EmailField()

    def __str__(self):
        return self.email


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    oredered = models.BooleanField(default=False)


class CartItems(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def sub_total(self):
        return '{}'.format (self.product.price * self.quantity)

    # def __str__(self):
    #     return self.product


class Wishlist(models.Model):
    product= models.ManyToManyField(Products)
    options = (
        ("Wishlisted", "Wishlisted"),
        ("in-cart", "in-cart")
        
    )
    status = models.CharField(max_length=300, choices=options, default="Wishlisted")
    user=models.ForeignKey(User,on_delete=models.CASCADE,null=True)


class Review(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    email = models.EmailField()
    review = models.TextField()
    rating = models.PositiveSmallIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.product} - {self.rating} stars'


class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=20)
    email = models.EmailField()
    add_1 = models.CharField(max_length=100)
    add_2 = models.CharField(max_length=100)
    city = models.CharField(max_length=50)
    country = models.CharField(max_length=50)
    zip_code = models.CharField(max_length=20)

    def __str__(self):
        return self.first_name

ecommerce_e/customer/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import *



# class CreateUserForm(UserCreationForm):
#     class Meta:
#         model = User
#         fields = ['username', 'email', 'password1', 'password2']


class CreateUserForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("This email address is already in use. Please use a different email address.")


class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'phone', 'email', 'add_1', 'add_2', 'city', 'country', 'zip_code']

ecommerce_e/customer/templates/base.html
{% load static %}
{% load i18n %}

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	 <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

	<title>Electro </title>

	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">

	<!-- Bootstrap -->
	<link type="text/css" rel="stylesheet" href="{% static 'ecss/css/bootstrap.min.css'%}"/>

	<!-- Slick -->
	<link type="text/css" rel="stylesheet" href="{% static 'ecss/css/slick.css' %}"/>
	<link type="text/css" rel="stylesheet" href="{% static 'ecss/css/slick-theme.css' %}"/>

	<!-- nouislider -->
	<link type="text/css" rel="stylesheet" href="{% static 'ecss/css/nouislider.min.css' %}"/>

	<!-- Font Awesome Icon -->
	<link rel="stylesheet" href="{% static 'ecss/css/font-awesome.min.css' %}"/>

	<!-- Custom stlylesheet -->
	
	<link type="text/css" rel="stylesheet" href="{% static 'ecss/css/style.css' %}">

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>



	
	
		
	<body>
		<!-- HEADER -->
		<header>
			<!-- TOP HEADER -->
			<div id="top-header">
				<div class="container">
					
					<ul class="header-links pull-right">
						
						
						
						{% if user.is_authenticated %}
						 
						<li><a href="{% url 'my-profile' %}"><i class="fa fa-home"></i>{% trans 'MY ACCOUNT' %}</a>	</li>
						<li><i class="fa fa-user-o"></i><a href="{% url 'logout' %}">{% trans 'LOGOUT' %}</a></li>
						{%else%}
						<li><a href="{% url 'register' %}"><i class="fa fa-dollar"></i> SIGN UP</a></li>

						<li><a href="{% url 'login' %}"><i class="fa fa-user-o"></i> SIGN IN</a></li>
						{%endif%}
					</ul>
				</div>
			</div>
			<!-- /TOP HEADER -->

			<!-- MAIN HEADER -->
			<div id="header">
				<!-- container -->
				<div class="container">
					<!-- row -->
					<div class="row">
						<!-- LOGO -->
						<div class="col-md-3">
							<div class="header-logo">
								<a href="#" class="logo">
									<img src="{% static 'ecss/img/logo.png' %}"alt="">
								</a>
							</div>
						</div>
						<!-- /LOGO -->

						<!-- SEARCH BAR -->
						
						<!-- /SEARCH BAR -->

						<!-- ACCOUNT -->
						<div class="col-md-3 clearfix">
							<div class="header-ctn">
								<!-- Wishlist -->
								
								<!-- /Wishlist -->

								<!-- Cart -->
								
									

											
										
								<!-- /Cart -->

								<!-- Menu Toogle -->
								<div class="menu-toggle">
									<a href="#">
										<i class="fa fa-bars"></i>
										<span>Menu</span>
									</a>
								</div>
								<!-- /Menu Toogle -->
							</div>
						</div>
						<!-- /ACCOUNT -->
					</div>
					<!-- row -->
				</div>
				<!-- container -->
			</div>
			<!-- /MAIN HEADER -->
		</header>
		<!-- /HEADER -->

		<!-- NAVIGATION -->
		<nav id="navigation">
			<!-- container -->
			<div class="container">
				<!-- responsive-nav -->
				<div id="responsive-nav">
					<!-- NAV -->
					<ul class="main-nav nav navbar-nav">
						
						{% if user.is_authenticated %}
						
						<li><a href="{% url 'shop' %}">{% trans 'SHOP' %}</a></li>
						<li><a href="{%url 'blog' %}">{% trans 'BLOG' %}</a></li>
                        <li> <a href="{% url 'cart' %}">{% trans 'CART' %}</a></li>
						<li class="active"><a href="{%url 'wishlist' %}">{% trans 'WISHLIST' %}</a></li>
						<li><a href="{% url 'my-orders' %}">{% trans 'MY ORDERS' %}</a></li>
                        
						{%else%}
						<li class="active"><a href="{%url 'home' %}">{% trans 'HOME' %}</a></li>
						<li><a href="{% url 'shop' %}">{% trans 'SHOP' %}</a></li>
						<li><a href="{% url 'contactus' %}">{% trans 'CONTACT' %}</a></li>
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" href="blog.html" id="navbarDropdown_1"
								role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								{% trans 'LANGUAGE' %}
							</a>
							<div class="dropdown-menu" aria-labelledby="navbarDropdown_1">
								{% get_current_language as LANGUAGE_CODE %}
								{% get_available_languages as LANGUAGES %}
								{% get_language_info_list for LANGUAGES as languages %}
								{% for lang in languages %}
								<a class="dropdown-item" href="/{{ lang.code }}/"> {{ lang.name_local }}</a>
								{% endfor %}
								
							</div>
						</li>
						{% endif %}
						{% if user.is_superuser %}
                        <li><a class="dropdown-item" href="{% url 'dashboard' %}">{% trans 'Dashboard' %}</a></li>
                                        {% endif %}
				
						
					</ul>
					<!-- /NAV -->
				</div>
				<!-- /responsive-nav -->
			</div>
			<!-- /container -->
		</nav>
		<!-- /NAVIGATION -->

		

		

        {% block body %}
        {% endblock %}

								


				

		<!-- FOOTER -->
		<footer id="footer">
			<!-- top footer -->
			<div class="section">
				<!-- container -->
				<div class="container">
					<!-- row -->
					<div class="row">
						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">About Us</h3>
								<p>Electro World is the new online e-commerce store-a continuously envolving shopping centre online</p>								
								<ul class="footer-links">
									<li><a href="#"><i class="fa fa-map-marker"></i>1734 Stonecoal Road</a></li>
									<li><a href="#"><i class="fa fa-phone"></i>+021-95-51-84</a></li>
									<li><a href="#"><i class="fa fa-envelope-o"></i>electroworld@email.com</a></li>
								</ul>
							</div>
						</div>

						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">Categories</h3>
								<ul class="footer-links">
									<li><a href="{% url 'shop' %}">Hot deals</a></li>
									<li><a href="{% url 'shop' %}">Laptops</a></li>
									<li><a href="{% url 'shop' %}">Smartphones</a></li>
									<li><a href="{% url 'shop' %}">Cameras</a></li>
									<li><a href="{% url 'shop' %}">Accessories</a></li>
								</ul>
							</div>
						</div>

						<div class="clearfix visible-xs"></div>

						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">Information</h3>
								<ul class="footer-links">
									
									<li><a href="contact.html">Contact Us</a></li>
									
									
									
								</ul>
							</div>
						</div>

						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">Service</h3>
								<ul class="footer-links">
									<li><a href="{% url 'my-profile' %}">My Account</a></li>
									<li><a href="{% url 'cart' %}">View Cart</a></li>
									<li><a href="{% url 'wishlist' %}">Wishlist</a></li>
									
								</ul>
							</div>
						</div>
					</div>
					<!-- /row -->
				</div>
				<!-- /container -->
			</div>
			<!-- /top footer -->



            


			<!-- bottom footer -->
			<div id="bottom-footer" class="section">
				<div class="container">
					<!-- row -->
					<div class="row">
						<div class="col-md-12 text-center">
							<ul class="footer-payments">
								<li><a href="#"><i class="fa fa-cc-visa"></i></a></li>
								<li><a href="#"><i class="fa fa-credit-card"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-paypal"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-mastercard"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-discover"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-amex"></i></a></li>
							</ul>
							<span class="copyright">
								<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
								Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | Developed by Technoland <a href="https://edensoft.com" target="_blank"></a>
							<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
							</span>
						</div>
					</div>
						<!-- /row -->
				</div>
				<!-- /container -->
			</div>
			<!-- /bottom footer -->

		</footer>
		<!-- /FOOTER -->
        <!-- jQuery Plugins -->
		<script src="{% static 'js/jquery.min.js' %}"></script>
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
		<script src="{% static 'js/slick.min.js' %}"></script>
		<script src="{% static 'js/nouislider.min.js' %}"></script>
		<script src="{% static 'js/jquery.zoom.min.js' %}"></script>
		<script src="{% static 'js/main.js' %}"></script>


		
	
	</body>
</html>

ecommerce_e/customer/templates/loginpage.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block title %} {% trans 'Login' %} {% endblock %}
{% block body %}


    <!-- breadcrumb start-->
    <section class="breadcrumb breadcrumb_bg">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <div class="breadcrumb_iner">
                        <div class="breadcrumb_iner_item">
                            <h2>{% trans 'Login To continue' %} !!!</h2>
                            <!-- <p>Home <span>-</span> Tracking Order</p> -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb start-->

    <!--================login_part Area =================-->
    <section class="vh-100" style="background-color: #eee;">
        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-lg-12 col-xl-11">
                    <div class="card text-black" style="border-radius: 25px;">
                        <div class="card-body p-md-5">
                            <div class="row justify-content-center">
                                <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
    
                                    <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">{% trans 'LOGIN' %}</p>
    
                                    <form action="" method="POST" >
                                        {%csrf_token%}
                                        <div class="d-flex flex-row align-items-center mb-4">
                                            <!-- <i class="fas fa-user fa-lg me-3 fa-fw"></i> -->
                                            <div class="form-outline flex-fill mb-0">
                                                <label class="form-label" for="form3Example1c">{% trans 'Username' %}</label><br>
    
                                                <input type="text" name="username" class="form-control" />
                                            </div>
                                        </div>
    
                                        <div class="d-flex flex-row align-items-center mb-4">
                                            <!-- <i class="fas fa-envelope fa-lg me-3 fa-fw"></i> -->
                                            <div class="form-outline flex-fill mb-0">
                                                <label class="form-label" for="form3Example3c">{% trans 'Password' %}</label><br>
    
                                                <input type="password" name="password" class="form-control" />
                                            </div>
                                        </div>
    
    
    
                                        <div>
                                        </div>
                                        <br>
    
    
                                        <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                                            <input type="submit" value="LOGIN" class="btn btn-primary btn-lg"></input>&nbsp;&nbsp;
    
                                            <a href="{%url 'register'%}" class="btn btn-primary btn-lg">{% trans 'Sign up' %}</a>
                                        </div>
                                        <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                                        <a href="{%url 'password_reset' %}">{% trans 'Forgot password' %}?</a>
                                    </div>
                                        <br>
                                    </form>
                                </div>
                                <!-- <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
    
                                    <img src="{% static 'img/algarib.png'%}"
                                        style="width:50%;margin-left: 40%; margin-top:18%" class="img-fluid"
                                        alt="Sample image">
    
                                </div> -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <br>
    
    <!--================login_part end =================-->
{% endblock %}

ecommerce_e/customer/templates/my-orders.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block title %} {% trans 'My orders' %} {% endblock %}
{% block body %}


  <!--================Home Banner Area =================-->
  <!-- breadcrumb start-->
  <section class="breadcrumb breadcrumb_bg">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8">
          <div class="breadcrumb_iner">
            <div class="breadcrumb_iner_item">
              <h2>{% trans 'My Orders' %}</h2>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- breadcrumb start-->

  <!--================Cart Area =================-->
  {%if orders%}
  <section class="cart_area padding_top">
    <div class="container">
      <div class="cart_inner">
        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th scope="col">{% trans 'Product' %}</th>
                <th scope="col">{% trans 'Price' %}</th>
                <th scope="col">{% trans 'Quantity' %}</th>
                <th scope="col">{% trans 'Total' %}</th>
              </tr>
            </thead>
            <tbody>
              {% for cart in orders %}
              {%for item in cart.cartitems_set.all %}
              <tr>
                <td>
                  <div class="media">
                    <div class="d-flex">
                      <img src="{{item.product.image_1.url}}" style="width:50px;height:50px;" alt="" />
                    </div>
                    <div class="media-body">
                      <p>{{item.product.name}}</p>
                    </div>
                  </div>
                </td>
                <td>
                  <h5>${{item.product.price}}</h5>
                </td>
                <td>
                  {{item.quantity}}
      

                 
                </td>
                <td>
                  <h5>${{item.sub_total }}</h5>
                </td>
              </tr>
              {% endfor %}
              {% endfor %}
              <!-- <tr>
                <td>
                  <div class="media">
                    <div class="d-flex">
                      <img src="img/product/single-product/cart-1.jpg" alt="" />
                    </div>
                    <div class="media-body">
                      <p>Minimalistic shop for multipurpose use</p>
                    </div>
                  </div>
                </td>
                <td>
                  <h5>$360.00</h5>
                </td>
                <td>
                  <div class="product_count"> -->
                    <!-- <input type="text" value="1" min="0" max="10" title="Quantity:"
                      class="input-text qty input-number" />
                    <button
                      class="increase input-number-increment items-count" type="button">
                      <i class="ti-angle-up"></i>
                    </button>
                    <button
                      class="reduced input-number-decrement items-count" type="button">
                      <i class="ti-angle-down"></i>
                    </button> -->
                    <!-- <span class="input-number-decrement"> <i class="ti-angle-down"></i></span>
                    <input class="input-number" type="text" value="1" min="0" max="10">
                    <span class="input-number-increment"> <i class="ti-angle-up"></i></span>
                  </div>
                </td>
                <td>
                  <h5>$720.00</h5>
                </td>
              </tr> -->
              <!-- <tr>
                <td>
                  <div class="media">
                    <div class="d-flex">
                      <img src="img/product/single-product/cart-1.jpg" alt="" />
                    </div>
                    <div class="media-body">
                      <p>Minimalistic shop for multipurpose use</p>
                    </div>
                  </div>
                </td>
                <td>
                  <h5>$360.00</h5>
                </td>
                <td>
                  <div class="product_count">
                    <span class="input-number-decrement"> <i class="ti-angle-down"></i></span>
                    <input class="input-number" type="text" value="1" min="0" max="10">
                    <span class="input-number-increment"> <i class="ti-angle-up"></i></span>
                  </div>
                </td>
                <td>
                  <h5>$720.00</h5>
                </td>
              </tr> -->
              <tr class="bottom_button">
                <td>
                  <!-- <a class="btn_1" href="#">Update Cart</a> -->
                </td>
                <td></td>
                <td></td>
                <td>
                  <div class="cupon_text float-right">
                    <!-- <a class="btn_1" href="#">Close Coupon</a> -->
                  </div>
                </td>
              </tr>
              <tr>
                <td></td>
                <td></td>
                <td>
                  <!-- <h5>Subtotal</h5> -->
                </td>
                <td>
                  <!-- <h5>${{total}}</h5> -->
                </td>
              </tr>
              <tr class="shipping_area">
                <!-- <td></td> -->
                <!-- <td></td> -->
                <!-- <td> -->
                  <!-- <h5>Shipping</h5> -->
                <!-- </td> -->
                <!-- <td> -->
                  <!-- <div class="shipping_box"> -->
                    <!-- <ul class="list">
                      <li>
                        <a href="#">Flat Rate: $5.00</a>
                      </li>
                      <li>
                        <a href="#">Free Shipping</a>
                      </li>
                      <li>
                        <a href="#">Flat Rate: $10.00</a>
                      </li>
                      <li class="active">
                        <a href="#">Local Delivery: $2.00</a>
                      </li>
                    </ul> -->
                    <!-- <h6>
                      Calculate Shipping
                      <i class="fa fa-caret-down" aria-hidden="true"></i>
                    </h6> -->
                    <!-- <select class="shipping_select"> -->
                      <!-- <option value="1">Bangladesh</option>
                      <option value="2">India</option>
                      <option value="4">Pakistan</option> -->
                    <!-- </select> -->
                    <!-- <select class="shipping_select section_bg"> -->
                      <!-- <option value="1">Select a State</option>
                      <option value="2">Select a State</option>
                      <option value="4">Select a State</option>
                    </select> -->
                    <!-- <input type="text" placeholder="Postcode/Zipcode" /> -->
                    <!-- <a class="btn_1" href="#">Update Details</a> -->
                  <!-- </div> -->
                <!-- </td> -->
              </tr>
            </tbody>
          </table>
          <div class="checkout_btn_inner float-right">
            <!-- <a class="btn_1" href="{% url 'shop' %}">Continue Shopping</a> -->
            <!-- <a class="btn_1 checkout_btn_1" href="{% url 'checkout' %}">Proceed to checkout</a> -->
          </div>
        </div>
      </div>
  </section>
  {%else%}
  <div class="container" style="margin-top: 100px;"><center><h3>{% trans 'You dont have made any orders' %} 
    !!!!</h3></center>
  <a href="{% url 'shop' %}" style="text-align: center;">{% trans 'Continue shopping' %} 
    </a></div>
  {%endif%}
  <!--================End Cart Area =================-->
  {% endblock %}

ecommerce_e/customer/templates/password_reset_complete.html
{%extends 'base.html'%}
{% block title %}Password reset {% endblock %}
{%block body%}
<div class="container">
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
            <h1><center>Hooray!</center></h1>
            <br>
            <br>
            <p><center>We've emailed you instructions for setting your password.</center></p>
            <p><center>If you don't receive an email, please make sure you've entered the address you registered with, thank you!.</center></p>
        </div>
        <div class="col-2"></div>
    </div>
</div>

{% endblock %}